import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';
import { MEMBER_USERNAME, clearDemoSession, demoAccountMessage, isDemoCredential, readDemoMember, restoreDemoSession, saveDemoSession, writeDemoMember } from './demo-mode.js';

const config = window.GYM_COMPANION_CONFIG;
const routine = window.GYM_COMPANION_ROUTINE || [];
const training = window.GYM_COMPANION_TRAINING || { catalog: [], levels: {}, templates: {}, habitDefaults: [] };
const app = document.querySelector('#app');
const preferenceKey = 'gym-companion-v3-member-auth-storage';
const createSupabase = remember => createClient(config.supabaseUrl, config.supabaseAnonKey, { auth: { detectSessionInUrl:true, persistSession:true, storage: remember ? localStorage : sessionStorage } });
let supabase = createSupabase(localStorage.getItem(preferenceKey) === 'remembered');
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[character]));
const logo = '<span class="brand"><img src="assets/fitness7-hero-logo.png" alt="Fitness 7"></span>';
const iso = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const scheduledDate = index => { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate()+((index+1-date.getDay()+7)%7)); return date; };
const emptyProgress = () => ({slots:{},choices:{},warmup:{},recovery:{},extras:{}});
const state = { user:null,profile:null,membership:null,plans:[],sessions:[],library:[],preferences:{template_key:'fitness7',tier:'intermediate'},extras:[],habitTemplate:training.habitDefaults,habitLog:{},screen:'home',dayIndex:0,detailItem:null,showExtras:false,message:'',demo:false };

function notice() { return state.message ? `<p class="notice">${escapeHtml(state.message)}</p>` : ''; }
function banner() { return state.demo ? '<aside class="preview-banner demo-banner"><b>Demo mode</b><span>Sample-only account — changes stay in this browser and are never sent to Fitness 7 or Supabase.</span></aside>' : ''; }
function header() { const name = state.profile?.full_name || state.user?.email || 'Member'; return `<header class="topbar">${logo}<span class="version-badge">V4</span><div class="topbar-actions"><button class="pill" data-screen="plan">My plan</button><button class="avatar" data-screen="profile" aria-label="Open profile">${escapeHtml(name.slice(0,1).toUpperCase())}</button></div></header>`; }
function currentTemplate() { return training.templates[state.preferences.template_key] || training.templates.ppl; }
const slugify = value => String(value ?? '').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function libraryBySlug(value) { const slug=slugify(value); return state.library.find(item => item.slug === value || item.slug === slug) || training.catalog.find(item => item.slug === value || item.slug === slug); }
function planSlots(plan) { return [...(plan?.member_plan_slots || [])].sort((a,b) => a.position-b.position); }
function habitCompleteCount() { return Object.values(state.habitLog || {}).filter(Boolean).length; }
function routineExercise(option) { if (!option) return null; const found=libraryBySlug(option.name); return found || {id:`routine-${slugify(option.name)}`,slug:slugify(option.name),name:option.name,image_path:option.image,alt_text:`Fitness 7 illustration: ${option.name}`,target_muscles:'',scheme:'',cue:''}; }
function routinePlan(dayIndex) { const day=routine[dayIndex]; if (!day) return null; return {id:`routine-plan-${dayIndex}`,day_index:dayIndex,focus:day.focus,warmup:day.warmup?.steps||[],recovery:day.finish?.steps||[],member_plan_slots:day.slots.map((slot,position)=>({id:`routine-slot-${dayIndex}-${position}`,position,exercise:routineExercise(slot.primary),alternative:routineExercise(slot.alternative),third:routineExercise(slot.third)}))}; }
function displayPlan(dayIndex) { const fallback=routinePlan(dayIndex), cloud=state.plans.find(item=>item.day_index===dayIndex); if (state.preferences.template_key==='fitness7') return fallback; return cloud; }
function detailItem(key) { const plan=displayPlan(state.dayIndex), slots=planSlots(plan); const all=[...slots.flatMap(slot=>[slot.exercise,slot.alternative,slot.third].filter(Boolean)),...plan?.warmup||[],...plan?.recovery||[],...state.extras.filter(item=>item.day_index===state.dayIndex).map(item=>item.exercise).filter(Boolean)]; return all.find(item=>slugify(item.slug||item.name||item.title)===key) || libraryBySlug(key) || {name:key,image_path:`assets/exercises/${key}.png`,alt_text:`Fitness 7 illustration: ${key}`}; }
function detailRecord(item) { const name=item.name||item.title||'Exercise'; const baseImage=item.image_path||item.image||`assets/exercises/${slugify(name)}.png`; const image=slugify(name)==='pull-up'?'assets/exercises/pull-up-detail-steps.png':baseImage; const target=item.target_muscles||item.targets||'Targeted movement'; const cue=item.cue||'Move slowly and keep the range comfortable.'; return {...item,name,image_path:baseImage,alt_text:item.alt_text||item.alt||`Fitness 7 illustration: ${name}`,target_muscles:target,scheme:item.scheme||item.duration||'',why:item.why||`Build control and prepare the ${target.toLowerCase()}.`,safetyCue:item.safetyCue||'Stop for sharp pain, dizziness, or unusual breathlessness.',detailSteps:item.detailSteps||[1,2,3].map((step,index)=>({image,alt:`${name} step ${index+1}`,instruction:index===0?'Set up with a stable, comfortable position.':index===1?cue:'Return slowly and keep control.'}))}; }
function optionalCandidates() { const source=training.templates.fitness7?.days?.[state.dayIndex], raw=source?.slots?.flatMap(slot=>[slot.primary,slot.alternative,slot.third].filter(Boolean))||[]; const base=new Set(raw.map(item=>slugify(item.name))); const selected=new Set(state.extras.filter(item=>item.day_index===state.dayIndex).map(item=>item.exercise_id)); const focus=(routine[state.dayIndex]?.focus||'').toLowerCase(); return state.library.filter(item=>!base.has(item.slug)&&!selected.has(item.id)&&((focus.includes('back')&&/row|pulldown|curl|lat|rear|hammer/.test(item.name.toLowerCase()))||(focus.includes('chest')&&/press|fly|push|triceps|extension/.test(item.name.toLowerCase()))||(focus.includes('leg')&&/squat|lunge|leg|calf|glute|rdl|hinge/.test(item.name.toLowerCase()))||(focus.includes('abs')&&/crunch|plank|dead bug|pallof|raise|bike|treadmill/.test(item.name.toLowerCase()))||(focus.includes('shoulder')&&/shoulder|lateral|rear|curl|pressdown|extension/.test(item.name.toLowerCase())))); }

function renderSignIn() {
  app.innerHTML = `<main class="shell auth">${logo}<section class="auth-panel"><p class="eyebrow">FITNESS 7 MEMBER</p><h1>Your workout is ready.</h1><p>Sign in to follow your personal training plan.</p>${config.demoMode ? '<p class="demo-hint">Demo: <b>sagar.paperwala003.member</b> · password <b>1234</b></p>' : ''}${notice()}<form id="sign-in" class="stack"><label class="field">Username or email<input name="username" required autocomplete="username"></label><label class="field">Password<input name="password" type="password" required autocomplete="current-password"></label><label class="remember-row"><input name="remember" type="checkbox"> Remember me</label><button class="button">Sign in</button></form><button class="link-button" data-show-reset>Forgot password?</button><form id="request-reset" class="stack hidden"><label class="field">Email<input name="email" type="email" required></label><button class="button secondary">Send reset link</button></form></section></main>`;
}
function renderHome() {
  const dayName = new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});
  app.innerHTML = `<main class="shell">${header()}${banner()}${notice()}<section class="home-hero">${logo}<p class="eyebrow">${dayName}</p><h1>${escapeHtml(currentTemplate().name || 'My training')}</h1><p>${escapeHtml(training.levels[state.preferences.tier]?.label || 'Intermediate')} · ${habitCompleteCount()}/${state.habitTemplate.length} habits today</p></section><section class="quick-grid"><button class="action-card" data-screen="plan"><span>◫</span><b>My training plan</b><small>Change split, level, or extras</small></button><button class="action-card" data-screen="habits"><span>✓</span><b>Today’s habits</b><small>${habitCompleteCount()}/${state.habitTemplate.length} complete</small></button></section><section class="day-grid">${routine.map((fallback,index) => { const plan=state.plans.find(item=>item.day_index===index), ready=Boolean(plan)||state.preferences.template_key==='fitness7'; const date=scheduledDate(index); return `<button class="day-card" data-day="${index}"><b>${escapeHtml(fallback.day)}</b><span>${escapeHtml(plan?.focus || currentTemplate().days?.[index]?.focus || 'Plan not assigned')}</span><small>${date.toLocaleDateString(undefined,{day:'numeric',month:'short'})}</small><em class="status">${ready?'Ready':'Apply plan'}</em></button>`; }).join('')}<button class="day-card" data-screen="profile"><b>My progress</b><span>History & membership</span><small>${state.sessions.length} saved workouts</small></button></section></main>`;
}
function guided(title, items, checks, key) { if (!items?.length) return ''; return `<details class="guided-panel" open><summary><span><p class="eyebrow">RECOMMENDED · OPTIONAL</p><h2>${title}</h2><p class="muted">Start with Priority 1; add more if time allows.</p></span><span class="guided-toggle">View</span></summary><section class="card workout-list">${items.map((item,index)=>`<article class="exercise"><div class="visual" style="background-image:url('${escapeHtml(item.image || item.image_path || '')}')" role="img" aria-label="${escapeHtml(item.alt || item.alt_text || item.title || item.name)}"></div><div><span class="priority-badge">${index===0?'Priority 1 — Do this first':index===1?'Priority 2 — Recommended':'Optional — If time allows'}</span><h3>${escapeHtml(item.title || item.name)}</h3><p>${escapeHtml(item.duration || item.scheme || '')}</p><p>${escapeHtml(item.cue || '')}</p><button class="link-button detail-button" data-detail-key="${escapeHtml(slugify(item.title||item.name||''))}">View exercise details →</button></div><label class="check"><input type="checkbox" data-check="${key}" data-index="${index}" ${checks?.[index]?'checked':''}><span>Done</span></label></article>`).join('')}</section></details>`; }
function snapshot(plan, extras) { return {focus:plan.focus,slots:planSlots(plan).map(slot=>({id:slot.id,exercise:slot.exercise,alternative:slot.alternative,third:slot.third})),warmup:plan.warmup||[],recovery:plan.recovery||[],extras:extras.map(item=>({id:item.exercise_id,exercise:item.exercise}))}; }
function renderWorkout() {
  const plan=displayPlan(state.dayIndex); if(!plan){ app.innerHTML=`<main class="shell">${header()}${banner()}<button class="link-button" data-screen="plan">Set up my plan</button><section class="card empty-state"><h1>No plan assigned</h1><p>Choose your split and level to create your future workouts.</p></section></main>`; return; }
  const date=iso(scheduledDate(state.dayIndex)), saved=state.sessions.find(item=>item.session_date===date), dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex), savedSnapshot=saved?.plan_snapshot, savedUsable=Boolean(savedSnapshot?.slots?.length>=planSlots(plan).length), snapBase=savedUsable?{...savedSnapshot,warmup:savedSnapshot.warmup?.length?savedSnapshot.warmup:plan.warmup,recovery:savedSnapshot.recovery?.length?savedSnapshot.recovery:plan.recovery}:snapshot(plan,dayExtras), snap={...snapBase,extras:dayExtras.map(item=>({id:item.exercise_id,exercise:item.exercise}))}, progress=saved?.progress||emptyProgress(), done=Object.values(progress.slots||{}).filter(Boolean).length;
  const renderExercise=(slot,index,extra=false)=>{ const choice=extra?0:(progress.choices?.[index]||0), exercise=choice===2&&slot.third?slot.third:choice===1&&slot.alternative?slot.alternative:slot.exercise; return `<article class="card exercise"><div class="visual" style="background-image:url('${escapeHtml(exercise?.image_path||exercise?.image||'')}')" role="img" aria-label="${escapeHtml(exercise?.alt_text||exercise?.alt||exercise?.name||'Exercise illustration')}"></div><div><h3>${escapeHtml(exercise?.name||'Exercise')}</h3><p>${escapeHtml(exercise?.target_muscles||'')} · ${escapeHtml(exercise?.scheme||'')}</p><p>${escapeHtml(exercise?.cue||'')}</p><button class="link-button detail-button" data-detail-key="${escapeHtml(slugify(exercise?.slug||exercise?.name||''))}">View exercise details →</button>${!extra&&(slot.alternative||slot.third)?`<div class="choices"><button class="pill choice ${choice===0?'selected':''}" data-choice="${index}" data-choice-index="0">Main</button>${slot.alternative?`<button class="pill choice ${choice===1?'selected':''}" data-choice="${index}" data-choice-index="1">Alternative</button>`:''}${slot.third?`<button class="pill choice ${choice===2?'selected':''}" data-choice="${index}" data-choice-index="2">Option 2</button>`:''}</div>`:''}</div><label class="check"><input type="checkbox" data-check="${extra?'extras':'slots'}" data-index="${index}" ${extra?progress.extras?.[index]?'checked':'':progress.slots?.[index]?'checked':''}><span>Done</span></label></article>`; };
  const optional=state.showExtras?`<section class="card optional-picker"><div class="section-title compact"><div><p class="eyebrow">${routine[state.dayIndex].day} ONLY</p><h2>Add optional exercise</h2><p>Choose up to two recurring extras for this weekday.</p></div></div><form id="extra-form" class="stack"><label class="field">Exercise<select name="exercise_id">${optionalCandidates().map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join('')}</select></label><div class="row-actions"><button type="button" class="pill" data-close-extras>Cancel</button><button class="button secondary" ${optionalCandidates().length?'':'disabled'}>Save optional exercise</button></div></form></section>`:'';
  app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ All days</button><section class="detail-head"><div><p class="eyebrow">${scheduledDate(state.dayIndex).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</p><h1>${escapeHtml(snap.focus)}</h1><p>${done}/${snap.slots.length} main exercises completed</p></div><button class="pill" data-open-extras>Add optional exercise</button></section>${guided('Warm-up',snap.warmup,progress.warmup,'warmup')}<section class="section-title"><div><p class="eyebrow">MAIN WORKOUT</p><h2>Your exercises</h2></div></section><section class="workout-list">${snap.slots.map((slot,index)=>renderExercise(slot,index)).join('')}</section>${snap.extras?.length?`<section class="section-title"><div><p class="eyebrow">OPTIONAL EXTRAS</p><h2>Extra work</h2></div></section><section class="workout-list">${snap.extras.map((slot,index)=>renderExercise(slot,index,true)).join('')}</section>`:''}${optional}${guided('Post-workout recovery',snap.recovery,progress.recovery,'recovery')}<section class="utility"><button class="button secondary" data-clear-session="${date}">Clear today’s checkmarks</button></section></main>`;
}
function renderDetail() { const item=detailRecord(state.detailItem||{}); app.innerHTML=`<main class="shell">${header()}${banner()}<button class="link-button" data-close-detail>‹ Back to workout</button><section class="detail-hero"><p class="eyebrow">EXERCISE GUIDE</p><h1>${escapeHtml(item.name)}</h1><p>${escapeHtml(item.target_muscles)} · ${escapeHtml(item.scheme)}</p></section><section class="detail-steps">${item.detailSteps.map((step,index)=>`<article class="card detail-step"><div class="visual detail-visual" style="background-image:url('${escapeHtml(step.image)}')" role="img" aria-label="${escapeHtml(step.alt)}"></div><div><span class="step-label">${index+1}</span><h2>${index===0?'Set up':index===1?'Move':'Return'}</h2><p>${escapeHtml(step.instruction)}</p></div></article>`).join('')}</section><section class="card detail-copy"><p><b>Why it matters</b><br>${escapeHtml(item.why)}</p><p><b>Form cue</b><br>${escapeHtml(item.cue)}</p><p><b>Safety</b><br>${escapeHtml(item.safetyCue)}</p></section></main>`; }
function renderPlan() {
  const template=currentTemplate(), tier=state.preferences.tier, source=template.days?.[state.dayIndex]||{}, baseIds=new Set(planSlots(displayPlan(state.dayIndex)).map(slot=>slot.exercise_id)), rawCandidates=source.candidates||source.slots?.flatMap(slot=>[slot.primary,slot.alternative,slot.third].filter(Boolean))||[], candidates=rawCandidates.map(item=>libraryBySlug(item.slug||item.name)).filter(item=>item&&(item.levels?.includes(tier) ?? true)&&!baseIds.has(item.id)); const extras=state.extras.filter(item=>item.day_index===state.dayIndex);
  app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">MY TRAINING PLAN</p><h1>Build your week</h1><p>Apply a level-based plan. Current workout history never changes.</p></div></section><section class="card"><form id="training-preferences" class="stack"><label class="field">Training template<select name="template_key"><option value="fitness7" ${state.preferences.template_key==='fitness7'?'selected':''}>Fitness 7 split (recommended)</option><option value="ppl" ${state.preferences.template_key==='ppl'?'selected':''}>PPL twice weekly</option></select></label><label class="field">Training level<select name="tier">${Object.entries(training.levels).map(([key,value])=>`<option value="${key}" ${tier===key?'selected':''}>${value.label} — ${value.subtitle}</option>`).join('')}</select></label><p class="muted">${training.levels[tier]?.slots||7} base exercises per day · up to 2 optional extras · ${escapeHtml(training.levels[tier]?.rir||'1–2 reps in reserve')}</p><button class="button">Apply my future plan</button></form></section><section class="section-title"><div><p class="eyebrow">${routine[state.dayIndex]?.day||'Day'} OPTIONS</p><h2>Optional extras</h2><p>Save up to two. They repeat on future matching days.</p></div></section><section class="card stack"><form id="extra-form" class="stack"><label class="field">Choose an extra<select name="exercise_id">${candidates.filter(item=>!extras.some(extra=>extra.exercise_id===item.id)).map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)} · ${escapeHtml(item.target_muscles)}</option>`).join('')}</select></label><button class="button secondary" ${extras.length>=2||!candidates.length?'disabled':''}>Add extra</button></form>${extras.map((item,index)=>`<article class="compact-row"><span>${escapeHtml(item.exercise?.name||'Extra exercise')}</span><button class="pill" data-remove-extra="${index}">Remove</button></article>`).join('')||'<p class="muted">No extras saved for this day yet.</p>'}</section><div class="day-picker">${routine.map((day,index)=>`<button class="day-chip ${state.dayIndex===index?'selected':''}" data-plan-day="${index}">${day.day.slice(0,3)}</button>`).join('')}</div></main>`;
}
function renderHabits() { const weekday=new Date().getDay(); app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">TODAY’S HABITS</p><h1>Keep the simple wins</h1><p>Binary tracking only—no calorie counting.</p></div></section><section class="card workout-list">${state.habitTemplate.map(item=>`<article class="compact-row"><span>${escapeHtml(item.label)}${item.id==='weekend-portions'&&weekday!==0&&weekday!==6?' <small>(weekend only)</small>':''}</span><label class="check"><input type="checkbox" data-habit="${escapeHtml(item.id)}" ${state.habitLog?.[item.id]?'checked':''}><span>Done</span></label></article>`).join('')}</section></main>`; }
function renderProfile(){ const membership=state.membership||{}; app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">MY ACCOUNT</p><h1>${escapeHtml(state.profile?.full_name||'Member')}</h1></div></section><section class="profile-grid"><article class="card"><h2>Membership</h2><p class="membership-badge ${escapeHtml(membership.status||'')}">${escapeHtml(membership.status||'Not set')}</p><p>${membership.ends_on?`Ends ${escapeHtml(membership.ends_on)}`:'Membership date not set'}</p></article><article class="card"><h2>Training</h2><p>${escapeHtml(currentTemplate().name||'Personal plan')} · ${escapeHtml(training.levels[state.preferences.tier]?.label||'Intermediate')}</p><button class="pill" data-screen="plan">Edit plan</button></article></section><section class="section-title"><div><p class="eyebrow">WORKOUT HISTORY</p><h2>Recent sessions</h2></div></section><section class="history-list">${state.sessions.length?state.sessions.map(session=>`<article class="card history-row"><div><b>${escapeHtml(session.plan_snapshot?.focus||'Workout')}</b><small>${escapeHtml(session.session_date)}</small></div><span>${Object.values(session.progress?.slots||{}).filter(Boolean).length}/${session.plan_snapshot?.slots?.length||0}</span></article>`).join(''):'<article class="card empty">No completed exercises yet.</article>'}</section><section class="utility"><button class="button secondary" data-sign-out>Sign out</button></section></main>`; }
function render(){ if(!state.user) return renderSignIn(); if(state.screen==='detail') return renderDetail(); if(state.screen==='workout') return renderWorkout(); if(state.screen==='plan') return renderPlan(); if(state.screen==='habits') return renderHabits(); if(state.screen==='profile') return renderProfile(); renderHome(); }

function demoData(){ const data=readDemoMember(routine); data.personal ||= {preferences:{template_key:'fitness7',tier:'intermediate'},extras:[],habitTemplate:training.habitDefaults,habitLog:{}}; data.personal.preferences ||= {template_key:'fitness7',tier:'intermediate'}; return data; }
function routineDemoPlans(){ return routine.map((day,day_index)=>{const plan=routinePlan(day_index);return {id:`demo-plan-${state.user.id}-${day_index}`,member_id:state.user.id,day_index,focus:plan.focus,warmup:plan.warmup,recovery:plan.recovery,member_plan_slots:plan.member_plan_slots.map(slot=>({...slot,exercise_id:slot.exercise?.id,alternative_exercise_id:slot.alternative?.id||null,third_exercise_id:slot.third?.id||null}))};}); }
function loadDemoMember(){ const data=demoData(); state.demo=true; state.user={id:data.profile.id,email:MEMBER_USERNAME}; state.profile=data.profile; state.membership=data.membership; state.sessions=data.sessions||[]; state.library=training.catalog.map((item,index)=>({...item,id:`demo-library-${item.slug||index}`})); state.preferences=data.personal.preferences; if(data.personal.planVersion!==2){data.plans=routineDemoPlans();data.personal.preferences={template_key:'fitness7',tier:'intermediate'};data.personal.planVersion=2;writeDemoMember(data);} state.plans=data.plans; state.extras=(data.personal.extras||[]).map(item=>({...item,exercise:state.library.find(ex=>ex.id===item.exercise_id)})); state.habitTemplate=data.personal.habitTemplate||training.habitDefaults; state.habitLog=data.personal.habitLog||{}; render(); }
async function loadMember(){ const core=await Promise.all([supabase.from('profiles').select('*').eq('id',state.user.id).single(),supabase.from('memberships').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('member_weekly_plans').select('*,member_plan_slots(*,exercise:exercise_library!member_plan_slots_exercise_id_fkey(*),alternative:exercise_library!member_plan_slots_alternative_exercise_id_fkey(*))').eq('member_id',state.user.id).order('day_index'),supabase.from('workout_sessions').select('*').eq('member_id',state.user.id).order('session_date',{ascending:false}).limit(45),supabase.from('exercise_library').select('*').eq('active',true).order('name')]); if(core[0].error) throw core[0].error; [state.profile,state.membership,state.plans,state.sessions]=[core[0].data,core[1].data,core[2].data||[],core[3].data||[]]; state.library=(core[4].data||[]).map(item=>({...item,levels:item.metadata?.levels||['beginner','intermediate','expert']})); const today=iso(new Date()); const feature=await Promise.all([supabase.from('member_training_preferences').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('member_extra_templates').select('*,exercise:exercise_library(*)').eq('member_id',state.user.id),supabase.from('member_habit_templates').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('daily_habit_logs').select('*').eq('member_id',state.user.id).eq('log_date',today).maybeSingle()]); state.preferences=feature[0].data||state.preferences; state.extras=feature[1].data||[]; state.habitTemplate=feature[2].data?.habits||training.habitDefaults; state.habitLog=feature[3].data?.checks||{}; render(); }
async function saveProgress(group,index,value){ const date=iso(scheduledDate(state.dayIndex)),plan=displayPlan(state.dayIndex),existing=state.sessions.find(item=>item.session_date===date),dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex),session=existing||{member_id:state.user.id,session_date:date,day_index:state.dayIndex,plan_snapshot:snapshot(plan,dayExtras),progress:emptyProgress()}; session.progress[group][index]=value; if(state.demo){state.sessions=[session,...state.sessions.filter(item=>item.session_date!==date)]; const data=demoData(); data.sessions=state.sessions; writeDemoMember(data);return;} const {data,error}=await supabase.from('workout_sessions').upsert(session,{onConflict:'member_id,session_date'}).select().single();if(error)throw error;state.sessions=[data,...state.sessions.filter(item=>item.session_date!==date)]; }
async function saveHabit(id,value){ state.habitLog[id]=value; if(state.demo){const data=demoData();data.personal.habitLog=state.habitLog;writeDemoMember(data);return;} const {error}=await supabase.from('daily_habit_logs').upsert({member_id:state.user.id,log_date:iso(new Date()),checks:state.habitLog},{onConflict:'member_id,log_date'});if(error)throw error; }
async function applyPlan(values){ const template=training.templates[values.template_key], tier=values.tier, limit=training.levels[tier].slots; const plans=[]; for(let index=0;index<6;index++){const source=template.days[index], rawCandidates=source.candidates||source.slots?.flatMap(slot=>[slot.primary,slot.alternative,slot.third].filter(Boolean))||[], candidates=rawCandidates.map(item=>libraryBySlug(item.slug||item.name)).filter(Boolean).filter(item=>!item.levels||item.levels.includes(tier)); const selected=values.template_key==='fitness7' ? source.slots.map(slot=>libraryBySlug(slot.primary.slug||slot.primary.name)).filter(Boolean) : candidates.slice(0,limit); if(selected.length< (values.template_key==='fitness7'?source.slots.length:limit)||selected.some(item=>!item?.id)) throw new Error(`Not enough ${training.levels[tier].label} exercises for ${routine[index].day}.`); plans.push({day_index:index,focus:source.focus,warmup:source.warmup?.steps||source.warmup||[],recovery:source.finish?.steps||source.recovery||[],slots:selected.map((exercise,position)=>({position,exercise_id:exercise.id,alternative_exercise_id:values.template_key==='fitness7'?libraryBySlug(source.slots[position].alternative?.slug||source.slots[position].alternative?.name)?.id||null:candidates[position+1]?.id||null}))}); } if(state.demo){const data=demoData();data.personal.preferences={template_key:values.template_key,tier};data.plans=plans.map(plan=>({id:`demo-plan-${state.user.id}-${plan.day_index}`,member_id:state.user.id,...plan,member_plan_slots:plan.slots.map(slot=>({...slot,id:`demo-slot-${plan.day_index}-${slot.position}`,exercise:state.library.find(item=>item.id===slot.exercise_id),alternative:state.library.find(item=>item.id===slot.alternative_exercise_id)}))}));data.personal.planVersion=2;writeDemoMember(data);loadDemoMember();return;} for(const planData of plans){const {data:plan,error}=await supabase.from('member_weekly_plans').upsert({member_id:state.user.id,day_index:planData.day_index,focus:planData.focus,warmup:planData.warmup,recovery:planData.recovery},{onConflict:'member_id,day_index'}).select().single();if(error)throw error;const remove=await supabase.from('member_plan_slots').delete().eq('plan_id',plan.id);if(remove.error)throw remove.error;const insert=await supabase.from('member_plan_slots').insert(planData.slots.map(slot=>({...slot,plan_id:plan.id})));if(insert.error)throw insert.error;} const pref=await supabase.from('member_training_preferences').upsert({member_id:state.user.id,template_key:values.template_key,tier},{onConflict:'member_id'});if(pref.error)throw pref.error; await loadMember(); }

document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{state.message='';if(button.dataset.detailKey){state.detailItem=detailItem(button.dataset.detailKey);state.screen='detail';render();return;}if(button.dataset.closeDetail!==undefined){state.detailItem=null;state.screen='workout';render();return;}if(button.dataset.openExtras!==undefined){state.showExtras=true;render();return;}if(button.dataset.closeExtras!==undefined){state.showExtras=false;render();return;}if(button.dataset.screen){state.screen=button.dataset.screen;state.showExtras=false;render();return;}if(button.dataset.day!==undefined){state.dayIndex=Number(button.dataset.day);state.screen='workout';state.showExtras=false;render();return;}if(button.dataset.planDay!==undefined){state.dayIndex=Number(button.dataset.planDay);render();return;}if(button.dataset.showReset!==undefined){document.querySelector('#request-reset').classList.toggle('hidden');return;}if(button.dataset.choice!==undefined){await saveProgress('choices',button.dataset.choice,Number(button.dataset.choiceIndex));render();return;}if(button.dataset.removeExtra!==undefined){const extras=state.extras.filter(item=>item.day_index===state.dayIndex);const target=extras[Number(button.dataset.removeExtra)];if(state.demo){const data=demoData();data.personal.extras=data.personal.extras.filter(item=>!(item.day_index===state.dayIndex&&item.exercise_id===target.exercise_id));writeDemoMember(data);loadDemoMember();}else{const {error}=await supabase.from('member_extra_templates').delete().eq('member_id',state.user.id).eq('day_index',state.dayIndex).eq('exercise_id',target.exercise_id);if(error)throw error;await loadMember();}return;}if(button.dataset.clearSession){if(state.demo){state.sessions=state.sessions.filter(item=>item.session_date!==button.dataset.clearSession);const data=demoData();data.sessions=state.sessions;writeDemoMember(data);}else{const {error}=await supabase.from('workout_sessions').delete().eq('member_id',state.user.id).eq('session_date',button.dataset.clearSession);if(error)throw error;state.sessions=state.sessions.filter(item=>item.session_date!==button.dataset.clearSession);}render();return;}if(button.dataset.signOut!==undefined){if(state.demo){clearDemoSession('member');state.demo=false;state.user=null;state.profile=null;render();}else{await supabase.auth.signOut();localStorage.removeItem(preferenceKey);sessionStorage.removeItem(preferenceKey);state.user=null;render();}}}catch(error){state.message=error.message;render();}});
document.addEventListener('change',async event=>{try{if(event.target.dataset.check!==undefined){await saveProgress(event.target.dataset.check,event.target.dataset.index,event.target.checked);render();}if(event.target.dataset.habit!==undefined){await saveHabit(event.target.dataset.habit,event.target.checked);render();}}catch(error){state.message=error.message;render();}});
document.addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));try{if(event.target.id==='sign-in'){const username=String(values.username||'').trim();if(config.demoMode&&isDemoCredential('member',username,values.password)){saveDemoSession('member',values.remember==='on');loadDemoMember();return;}if(!username.includes('@'))throw new Error(demoAccountMessage);const remember=values.remember==='on';localStorage.removeItem(preferenceKey);sessionStorage.removeItem(preferenceKey);(remember?localStorage:sessionStorage).setItem(preferenceKey,remember?'remembered':'temporary');supabase=createSupabase(remember);const {data,error}=await supabase.auth.signInWithPassword({email:username,password:values.password});if(error)throw error;state.user=data.user;await loadMember();return;}if(event.target.id==='request-reset'){const {error}=await supabase.auth.resetPasswordForEmail(values.email,{redirectTo:location.origin});if(error)throw error;state.message='Check your email for the secure reset link.';render();}if(event.target.id==='training-preferences'){await applyPlan(values);state.message='Your future training plan is ready.';state.screen='home';render();}if(event.target.id==='extra-form'){const dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex);if(dayExtras.length>=2)throw new Error('Keep optional extras to two for recovery.');const exercise=state.library.find(item=>item.id===values.exercise_id)||training.catalog.find(item=>item.id===values.exercise_id);if(!exercise)throw new Error('Choose an approved exercise.');if(state.demo){const data=demoData();data.personal.extras.push({day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id});writeDemoMember(data);loadDemoMember();}else{const {error}=await supabase.from('member_extra_templates').upsert({member_id:state.user.id,day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id},{onConflict:'member_id,day_index,position'});if(error)throw error;await loadMember();}state.showExtras=false;state.screen='workout';render();}}catch(error){state.message=error.message;render();}});
if(config.demoMode&&restoreDemoSession('member'))loadDemoMember();else{const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(state.user)await loadMember();else render();}
