import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';
import { MEMBER_USERNAME, clearDemoSession, demoAccountMessage, isDemoCredential, readDemoMember, restoreDemoSession, saveDemoSession, writeDemoMember } from './demo-mode.js';

const config = window.GYM_COMPANION_CONFIG;
const routine = window.GYM_COMPANION_ROUTINE || [];
const v5Routine = window.GYM_COMPANION_V5_ROUTINE || [];
const training = window.GYM_COMPANION_TRAINING || { catalog: [], levels: {}, templates: {}, habitDefaults: [] };
const app = document.querySelector('#app');
const preferenceKey = 'gym-companion-v3-member-auth-storage';
const createSupabase = remember => config.supabaseUrl && config.supabaseAnonKey ? createClient(config.supabaseUrl, config.supabaseAnonKey, { auth: { detectSessionInUrl:true, persistSession:true, storage: remember ? localStorage : sessionStorage } }) : null;
let supabase = createSupabase(localStorage.getItem(preferenceKey) === 'remembered');
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[character]));
const logo = '<span class="brand"><img src="assets/fitness7-hero-logo.png" alt="Fitness 7"></span>';
const iso = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const scheduledDate = index => { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate()+((index+1-date.getDay()+7)%7)); return date; };
const emptyProgress = () => ({slots:{},choices:{},warmup:{},recovery:{},extras:{}});
const dayGroups = [['back','biceps'],['chest','triceps'],['core'],['legs'],['shoulders','biceps','triceps'],['core','biceps','triceps']];
const state = { user:null,profile:null,membership:null,plans:[],sessions:[],library:[],preferences:{template_key:'v5ppl',tier:'intermediate'},extras:[],guidedExtras:{},habitTemplate:training.habitDefaults,habitLog:{},screen:'home',dayIndex:0,detailItem:null,showExtras:false,calendarMonth:new Date(new Date().getFullYear(),new Date().getMonth(),1),historyDate:null,message:'',demo:false };

function notice() { return state.message ? `<p class="notice">${escapeHtml(state.message)}</p>` : ''; }
function banner() { return state.demo ? '<aside class="preview-banner demo-banner"><b>Demo mode</b><span>Sample-only account — changes stay in this browser and are never sent to Fitness 7 or Supabase.</span></aside>' : ''; }
function header() { const name = state.profile?.full_name || state.user?.email || 'Member'; return `<header class="topbar">${logo}<span class="version-badge">V5</span><div class="topbar-actions"><button class="pill" data-screen="plan">My plan</button><button class="avatar" data-screen="profile" aria-label="Open profile">${escapeHtml(name.slice(0,1).toUpperCase())}</button></div></header>`; }
function currentTemplate() { return training.templates[state.preferences.template_key] || training.templates.v5ppl; }
const slugify = value => String(value ?? '').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function targetGroupsForDay(index) { return currentTemplate()?.days?.[index]?.targetGroups || dayGroups[index] || []; }
function libraryBySlug(value) { const slug=slugify(value); return normalizeExercise(state.library.find(item => item.slug === value || item.slug === slug) || training.catalog.find(item => item.slug === value || item.slug === slug)); }
function planSlots(plan) { return [...(plan?.member_plan_slots || [])].sort((a,b) => a.position-b.position); }
function habitCompleteCount() { return Object.values(state.habitLog || {}).filter(Boolean).length; }
function inferredGroups(item) {
  if (Array.isArray(item?.targetGroups) && item.targetGroups.length) return item.targetGroups;
  const text=`${item?.target_muscles||''} ${item?.targets||''} ${item?.movement_pattern||''} ${item?.name||''}`.toLowerCase();
  const groups=new Set();
  if (/chest|pectoral|fly|horizontal press/.test(text)) groups.add('chest');
  if (/triceps|elbow extension/.test(text)) groups.add('triceps');
  if (/lat|back|row|rear delt|pulldown|pullover|shoulder extension/.test(text)) groups.add('back');
  if (/biceps|brachialis|forearm|curl|elbow flexion/.test(text)) groups.add('biceps');
  if (/shoulder|side delt|front delt|lateral|vertical press|abduction/.test(text)) groups.add('shoulders');
  if (/quad|glute|hamstring|calf|squat|lunge|hinge|leg|hip extension|knee flexion|knee extension/.test(text)) groups.add('legs');
  if (/abs|core|oblique|trunk|plank|pallof|dead bug|conditioning|cardio|treadmill|bike/.test(text)) groups.add('core');
  return [...groups];
}
function normalizeExercise(item) { if(!item)return item; const normalized={...item,targetGroups:inferredGroups(item)}; normalized.exerciseType ||= isStretchOrMobility(normalized)?'mobility':'strength'; normalized.isOptional ||= false; return normalized; }
function isStretchOrMobility(item) {
  const text=`${item?.exerciseType||''} ${item?.movement_pattern||''} ${item?.name||''} ${item?.title||''}`.toLowerCase();
  const groups=inferredGroups(item);
  return groups.includes('mobility') || /stretch|mobility|warm.?up|recovery|cooldown/.test(text);
}
function isGuidedMovement(item, panel) {
  if (!item || isStretchOrMobility(item)) return false;
  const text=`${item.exerciseType||''} ${item.movement_pattern||''} ${item.name||''} ${item.title||''}`.toLowerCase();
  if (panel==='warmup') return /activation|rehearsal|bodyweight|mobility|warm/.test(text) || inferredGroups(item).includes('core');
  return /cardio|bike|treadmill|walk|zone 2|cooldown|recovery/.test(text);
}
function routineExercise(option) { if (!option) return null; const found=libraryBySlug(option.name); return normalizeExercise(found || {id:`routine-${slugify(option.name)}`,slug:slugify(option.name),name:option.name,image_path:option.image,alt_text:`Fitness 7 illustration: ${option.name}`,target_muscles:'',scheme:'',cue:''}); }
function routinePlan(dayIndex, source=routine, label='routine') { const day=source[dayIndex]; if (!day) return null; return {id:`${label}-plan-${dayIndex}`,day_index:dayIndex,focus:day.focus,warmup:day.warmup?.steps||[],recovery:day.finish?.steps||[],member_plan_slots:day.slots.map((slot,position)=>({id:`${label}-slot-${dayIndex}-${position}`,position,exercise:routineExercise(slot.primary),alternative:routineExercise(slot.alternative),third:routineExercise(slot.third)}))}; }
function displayPlan(dayIndex) { if (state.preferences.template_key==='fitness7') return routinePlan(dayIndex, routine, 'fitness7'); if (state.preferences.template_key==='v5ppl') return routinePlan(dayIndex, v5Routine, 'v5'); return state.plans.find(item=>item.day_index===dayIndex) || routinePlan(dayIndex, v5Routine, 'v5'); }
function detailItem(key) { const plan=displayPlan(state.dayIndex), slots=planSlots(plan); const all=[...slots.flatMap(slot=>[slot.exercise,slot.alternative,slot.third].filter(Boolean)),...plan?.warmup||[],...plan?.recovery||[],...state.extras.filter(item=>item.day_index===state.dayIndex).map(item=>item.exercise).filter(Boolean)]; return all.find(item=>slugify(item.slug||item.name||item.title)===key) || libraryBySlug(key) || {name:key,image_path:`assets/exercises/${key}.png`,alt_text:`Fitness 7 illustration: ${key}`}; }
function phaseAsset(baseImage, phase) { return String(baseImage).replace(/\.png$/i, `-phase-${phase}.png`); }
function detailRecord(item) {
  const name=item.name||item.title||'Exercise';
  const baseImage=item.image_path||item.image||`assets/exercises/${slugify(name)}.png`;
  const target=item.target_muscles||item.targets||'Targeted movement';
  const cue=item.cue||'Move slowly and keep the range comfortable.';
  const equipment=item.equipment||item.equipment_required||'the available setup';
  const supplied=Array.isArray(item.detailSteps)?item.detailSteps:[];
  const phases=[['setup', 'Set up', item.setupInstruction||`Set up ${equipment} with a stable base and your joints stacked.`], ['move', 'Move', item.executionInstruction||cue], ['return', 'Return', item.returnInstruction||'Return slowly to the start and keep tension under control.']];
  return {...item,name,image_path:baseImage,alt_text:item.alt_text||item.alt||`Fitness 7 illustration: ${name}`,target_muscles:target,scheme:item.scheme||item.duration||'',why:item.why||`Build control and prepare the ${target.toLowerCase()}.`,safetyCue:item.safetyCue||'Stop for sharp pain, dizziness, or unusual breathlessness.',imageSet:{setup:phaseAsset(baseImage,'setup'),move:phaseAsset(baseImage,'move'),return:phaseAsset(baseImage,'return')},detailSteps:phases.map(([phase,label,instruction],index)=>({...supplied[index],phase,label,image:phaseAsset(baseImage,phase),alt:supplied[index]?.alt||`Fitness 7 ${name} ${label.toLowerCase()} position`,instruction}))};
}
function optionalCandidates() {
  const source=currentTemplate()?.days?.[state.dayIndex]||{}, raw=source?.slots?.flatMap(slot=>[slot.primary,slot.alternative,slot.third].filter(Boolean))||source?.candidates||[];
  const base=new Set(raw.map(item=>slugify(item.name))), selected=new Set(state.extras.filter(item=>item.day_index===state.dayIndex).map(item=>item.exercise_id)), allowed=new Set(targetGroupsForDay(state.dayIndex));
  return state.library.map(normalizeExercise).filter(item=>!base.has(item.slug)&&!selected.has(item.id)&&!isStretchOrMobility(item)&&inferredGroups(item).length>0&&inferredGroups(item).every(group=>allowed.has(group)));
}
function guidedCandidates(panel, plan) {
  const allowed=new Set(targetGroupsForDay(state.dayIndex));
  return state.library.map(normalizeExercise).filter(item=>!isStretchOrMobility(item)&&isGuidedMovement(item,panel)&&inferredGroups(item).some(group=>allowed.has(group))).slice(0,8).map(item=>({...item,guidedPanel:panel}));
}
function optionalCards(items, mode='extra') { return items.length ? `<div class="extra-option-grid">${items.map(item=>`<article class="extra-option"><span class="extra-option-visual visual" style="background-image:url('${escapeHtml(item.image_path||item.image||'')}')" role="img" aria-label="${escapeHtml(item.alt_text||item.alt||`${item.name} illustration`)}"></span><span class="extra-option-copy"><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.target_muscles||item.targets||'')}</small><small>${escapeHtml(item.scheme||'')}</small><button type="button" class="link-button detail-button" data-detail-key="${escapeHtml(slugify(item.slug||item.name||''))}">View details →</button><button type="button" class="pill ${mode==='guided'?'guided-add':'extra-add'}" ${mode==='guided'?`data-add-guided-panel="${escapeHtml(item.guidedPanel||'warmup')}" data-add-guided="${escapeHtml(item.id)}"`: `data-add-extra="${escapeHtml(item.id)}"`}>＋ Add</button></span></article>`).join('')}</div>` : '<p class="muted">No more approved options are available for this day.</p>'; }
async function addExtra(exerciseId) {
  const dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex);
  if(dayExtras.length>=2) throw new Error('Keep optional extras to two for recovery.');
  const exercise=state.library.map(normalizeExercise).find(item=>item.id===exerciseId)||training.catalog.find(item=>item.id===exerciseId);
  if(!exercise) throw new Error('Choose an approved exercise.');
  if(isStretchOrMobility(exercise) || !inferredGroups(exercise).length || !inferredGroups(exercise).every(group=>targetGroupsForDay(state.dayIndex).includes(group))) throw new Error('That exercise is not compatible with this day.');
  if(state.demo){ const data=demoData(); data.personal.extras.push({day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id}); writeDemoMember(data); loadDemoMember(); return; }
  const {error}=await supabase.from('member_extra_templates').upsert({member_id:state.user.id,day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id},{onConflict:'member_id,day_index,position'}); if(error) throw error; await loadMember();
}
function sessionForDate(date) { return state.sessions.find(item=>item.session_date===date && item.source_version==='v5') || null; }
function calendarSessionForDate(date) { return sessionForDate(date) || state.sessions.find(item=>item.session_date===date) || null; }
function zoneComplete(progress, key, expected) { return expected>0 && Object.values(progress?.[key]||{}).filter(Boolean).length>=expected; }
function ringStatus(session) { const snap=session?.plan_snapshot||{}, progress=session?.progress||emptyProgress(); return {main:zoneComplete(progress,'slots',snap.slots?.length||0),warmup:zoneComplete(progress,'warmup',snap.warmup?.length||0),recovery:zoneComplete(progress,'recovery',snap.recovery?.length||0)}; }
function monthLabel() { return state.calendarMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'}); }
function calendarMarkup(compact=false) {
  const cursor=state.calendarMonth, year=cursor.getFullYear(), month=cursor.getMonth(), first=new Date(year,month,1), start=(first.getDay()+6)%7, days=new Date(year,month+1,0).getDate();
  const cells=[]; for(let index=0;index<start;index++) cells.push('<span class="calendar-cell empty"></span>');
  for(let day=1;day<=days;day++){ const date=iso(new Date(year,month,day)), session=calendarSessionForDate(date), rings=ringStatus(session), classes=`calendar-cell ${session?'has-session':''}`; cells.push(`<button class="${classes}" data-history-date="${session?date:''}" ${session?'':'disabled'} aria-label="${date}${session?` ${rings.main?'main complete, ':''}${rings.warmup?'warm-up complete, ':''}${rings.recovery?'recovery complete':''}`:' no saved workout'}"><time>${day}</time><span class="rings"><i class="ring ring-main ${rings.main?'complete':''}"></i><i class="ring ring-warmup ${rings.warmup?'complete':''}"></i><i class="ring ring-recovery ${rings.recovery?'complete':''}"></i></span></button>`); }
  return `<section class="calendar-panel ${compact?'calendar-compact':''}"><div class="calendar-head"><div><p class="eyebrow">WORKOUT HISTORY</p><h2>${monthLabel()}</h2></div><div class="calendar-controls"><button class="icon-btn" data-calendar-shift="-1" aria-label="Previous month">−</button><button class="icon-btn" data-calendar-shift="1" aria-label="Next month">＋</button>${compact?'<button class="link-button" data-screen="profile">Full view →</button>':''}</div></div><div class="calendar-weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-grid">${cells.join('')}</div><div class="calendar-legend"><span><i class="ring ring-main complete"></i>Main</span><span><i class="ring ring-warmup complete"></i>Warm-up</span><span><i class="ring ring-recovery complete"></i>Recovery</span></div></section>`;
}

function renderSignIn() {
  app.innerHTML = `<main class="shell auth">${logo}<section class="auth-panel"><p class="eyebrow">FITNESS 7 MEMBER</p><h1>Your workout is ready.</h1><p>Sign in to follow your personal training plan.</p>${config.demoMode ? '<p class="demo-hint">Demo: <b>sagar.paperwala003.member</b> · password <b>1234</b></p>' : ''}${notice()}<form id="sign-in" class="stack"><label class="field">Username or email<input name="username" required autocomplete="username"></label><label class="field">Password<input name="password" type="password" required autocomplete="current-password"></label><label class="remember-row"><input name="remember" type="checkbox"> Remember me</label><button class="button">Sign in</button></form><button class="link-button" data-show-reset>Forgot password?</button><form id="request-reset" class="stack hidden"><label class="field">Email<input name="email" type="email" required></label><button class="button secondary">Send reset link</button></form></section></main>`;
}
function renderHome() {
  const dayName = new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});
  app.innerHTML = `<main class="shell">${header()}${banner()}${notice()}<section class="home-hero">${logo}<p class="eyebrow">${dayName}</p><h1>${escapeHtml(currentTemplate().name || 'My training')}</h1><p>${escapeHtml(training.levels[state.preferences.tier]?.label || 'Intermediate')} · ${state.sessions.length} saved sessions</p></section><section class="quick-grid"><button class="action-card" data-screen="plan"><span>◫</span><b>My training plan</b><small>Change split, level, or extras</small></button><button class="action-card" data-screen="profile"><span>◌</span><b>My progress</b><small>Open your monthly completion rings</small></button></section><section class="day-grid">${routine.map((fallback,index) => { const plan=state.plans.find(item=>item.day_index===index), ready=Boolean(plan)||state.preferences.template_key==='fitness7'; const date=scheduledDate(index); return `<button class="day-card" data-day="${index}"><b>${escapeHtml(fallback.day)}</b><span>${escapeHtml(plan?.focus || currentTemplate().days?.[index]?.focus || 'Plan not assigned')}</span><small>${date.toLocaleDateString(undefined,{day:'numeric',month:'short'})}</small><em class="status">${ready?'Ready':'Apply plan'}</em></button>`; }).join('')}</section>${calendarMarkup(true)}</main>`;
}
function guided(title, items, checks, key, options=[]) { if (!items?.length) return ''; return `<details class="guided-panel" open><summary><span><p class="eyebrow">RECOMMENDED · OPTIONAL</p><h2>${title}</h2><p class="muted">Start with Priority 1; add more if time allows.</p></span><span class="guided-toggle">View</span></summary><section class="card workout-list">${items.map((item,index)=>`<article class="exercise"><div class="visual" style="background-image:url('${escapeHtml(item.image || item.image_path || '')}')" role="img" aria-label="${escapeHtml(item.alt || item.alt_text || item.title || item.name)}"></div><div><span class="priority-badge">${index===0?'Priority 1 — Do this first':index===1?'Priority 2 — Recommended':'Optional — If time allows'}</span><h3>${escapeHtml(item.title || item.name)}</h3><p>${escapeHtml(item.duration || item.scheme || '')}</p><p>${escapeHtml(item.cue || '')}</p><button class="link-button detail-button" data-detail-key="${escapeHtml(slugify(item.title||item.name||''))}">View exercise details →</button></div><label class="check"><input type="checkbox" data-check="${key}" data-index="${index}" ${checks?.[index]?'checked':''}><span>Done</span></label></article>`).join('')}</section>${options.length?`<section class="guided-options"><div class="section-title compact"><div><p class="eyebrow">OPTIONAL ADD-ONS</p><h3>Need a different option?</h3><p class="muted">Choose a relevant movement if you have extra time.</p></div></div>${optionalCards(options, 'guided')}</section>`:''}</details>`; }
function snapshot(plan, extras, guidedExtras={}) { return {source_version:'v5',focus:plan.focus,slots:planSlots(plan).map(slot=>({id:slot.id,exercise:slot.exercise,alternative:slot.alternative,third:slot.third})),warmup:plan.warmup||[],recovery:plan.recovery||[],warmupExtras:guidedExtras.warmup||[],recoveryExtras:guidedExtras.recovery||[],extras:extras.map(item=>({id:item.exercise_id,exercise:item.exercise}))}; }
async function addGuidedExtra(panel, exerciseId) {
  const date=iso(scheduledDate(state.dayIndex)), plan=displayPlan(state.dayIndex), existing=sessionForDate(date), dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex);
  const exercise=state.library.map(normalizeExercise).find(item=>item.id===exerciseId)||training.catalog.find(item=>item.id===exerciseId);
  if(!exercise || !isGuidedMovement(exercise,panel)) throw new Error('Choose a relevant guided movement.');
  const current=existing?.plan_snapshot?.[panel==='warmup'?'warmupExtras':'recoveryExtras']||[];
  if(current.some(item=>item.id===exercise.id)) return;
  const guidedExtras={warmup:existing?.plan_snapshot?.warmupExtras||[],recovery:existing?.plan_snapshot?.recoveryExtras||[]};
  guidedExtras[panel].push(exercise);
  const session=existing||{member_id:state.user.id,session_date:date,day_index:state.dayIndex,source_version:'v5',plan_snapshot:snapshot(plan,dayExtras,guidedExtras),progress:emptyProgress()};
  session.plan_snapshot={...session.plan_snapshot,[panel==='warmup'?'warmupExtras':'recoveryExtras']:guidedExtras[panel]};
  if(state.demo){state.sessions=[session,...state.sessions.filter(item=>item.session_date!==date)];const data=demoData();data.sessions=state.sessions;writeDemoMember(data);render();return;}
  const {data,error}=await supabase.from('workout_sessions').upsert(session,{onConflict:'member_id,session_date,source_version'}).select().single(); if(error) throw error; state.sessions=[data,...state.sessions.filter(item=>!(item.session_date===date&&item.source_version==='v5'))]; render();
}
function renderWorkout() {
  const plan=displayPlan(state.dayIndex); if(!plan){ app.innerHTML=`<main class="shell">${header()}${banner()}<button class="link-button" data-screen="plan">Set up my plan</button><section class="card empty-state"><h1>No plan assigned</h1><p>Choose your split and level to create your future workouts.</p></section></main>`; return; }
  const date=iso(scheduledDate(state.dayIndex)), saved=sessionForDate(date), dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex), savedSnapshot=saved?.plan_snapshot, savedUsable=Boolean(savedSnapshot?.slots?.length>=planSlots(plan).length), snapBase=savedUsable?{...savedSnapshot,warmup:savedSnapshot.warmup?.length?savedSnapshot.warmup:plan.warmup,recovery:savedSnapshot.recovery?.length?savedSnapshot.recovery:plan.recovery}:snapshot(plan,dayExtras), snap={...snapBase,warmup:[...(snapBase.warmup||[]),...(snapBase.warmupExtras||[])],recovery:[...(snapBase.recovery||[]),...(snapBase.recoveryExtras||[])],extras:dayExtras.map(item=>({id:item.exercise_id,exercise:item.exercise}))}, progress=saved?.progress||emptyProgress(), done=Object.values(progress.slots||{}).filter(Boolean).length;
  const renderExercise=(slot,index,extra=false)=>{ const choice=extra?0:(progress.choices?.[index]||0), exercise=choice===2&&slot.third?slot.third:choice===1&&slot.alternative?slot.alternative:slot.exercise; return `<article class="card exercise"><div class="visual" style="background-image:url('${escapeHtml(exercise?.image_path||exercise?.image||'')}')" role="img" aria-label="${escapeHtml(exercise?.alt_text||exercise?.alt||exercise?.name||'Exercise illustration')}"></div><div><h3>${escapeHtml(exercise?.name||'Exercise')}</h3><p>${escapeHtml(exercise?.target_muscles||'')} · ${escapeHtml(exercise?.scheme||'')}</p><p>${escapeHtml(exercise?.cue||'')}</p><button class="link-button detail-button" data-detail-key="${escapeHtml(slugify(exercise?.slug||exercise?.name||''))}">View exercise details →</button>${!extra&&(slot.alternative||slot.third)?`<div class="choices"><button class="pill choice ${choice===0?'selected':''}" data-choice="${index}" data-choice-index="0">Main</button>${slot.alternative?`<button class="pill choice ${choice===1?'selected':''}" data-choice="${index}" data-choice-index="1">Alternative</button>`:''}${slot.third?`<button class="pill choice ${choice===2?'selected':''}" data-choice="${index}" data-choice-index="2">Option 2</button>`:''}</div>`:''}</div><label class="check"><input type="checkbox" data-check="${extra?'extras':'slots'}" data-index="${index}" ${extra?progress.extras?.[index]?'checked':'':progress.slots?.[index]?'checked':''}><span>Done</span></label></article>`; };
  const activeDay=currentTemplate().days?.[state.dayIndex]||v5Routine[state.dayIndex];
  const optional=state.showExtras?`<section class="card optional-picker"><div class="section-title compact"><div><p class="eyebrow">${activeDay?.day||routine[state.dayIndex].day} ONLY</p><h2>Add optional exercise</h2><p>Only ${activeDay?.focus?.toLowerCase()||''} options are shown. Tap ＋ Add to save a recurring extra.</p></div></div>${optionalCards(optionalCandidates())}<button type="button" class="pill" data-close-extras>Close</button></section>`:'';
  app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ All days</button><section class="detail-head"><div><p class="eyebrow">${scheduledDate(state.dayIndex).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</p><h1>${escapeHtml(snap.focus)}</h1><p>${done}/${snap.slots.length} main exercises completed</p></div></section>${guided('Warm-up',snap.warmup,progress.warmup,'warmup',guidedCandidates('warmup',plan))}<section class="section-title"><div><p class="eyebrow">MAIN WORKOUT</p><h2>Your exercises</h2></div></section><section class="workout-list">${snap.slots.map((slot,index)=>renderExercise(slot,index)).join('')}</section><section class="post-main-actions"><button class="button" data-open-extras>＋ Add optional exercise</button><small>Up to two recurring extras for this weekday</small></section>${snap.extras?.length?`<section class="section-title"><div><p class="eyebrow">OPTIONAL EXTRAS</p><h2>Extra work</h2><p class="muted">Tap − to remove a recurring extra.</p></div></section><section class="workout-list">${snap.extras.map((slot,index)=>`${renderExercise(slot,index,true)}<button class="pill extra-remove" data-remove-extra="${index}">− Remove extra</button>`).join('')}</section>`:''}${optional}${guided('Post-workout recovery',snap.recovery,progress.recovery,'recovery',guidedCandidates('recovery',plan))}<section class="utility"><button class="button secondary" data-clear-session="${date}">Clear today’s checkmarks</button></section></main>`;
}
function renderDetail() { const item=detailRecord(state.detailItem||{}); app.innerHTML=`<main class="shell">${header()}${banner()}<button class="link-button" data-close-detail>‹ Back to workout</button><section class="detail-hero"><p class="eyebrow">EXERCISE GUIDE</p><h1>${escapeHtml(item.name)}</h1><p>${escapeHtml(item.target_muscles)} · ${escapeHtml(item.scheme)}</p></section><section class="detail-steps">${item.detailSteps.map((step,index)=>`<article class="card detail-step"><div class="visual detail-visual" style="background-image:url('${escapeHtml(step.image)}')" role="img" aria-label="${escapeHtml(step.alt)}"></div><div><span class="step-label">${index+1}</span><span class="phase-name">${escapeHtml(step.label||['Set up','Move','Return'][index])}</span><p>${escapeHtml(step.instruction)}</p></div></article>`).join('')}</section><section class="card detail-copy"><p><b>Why it matters</b><br>${escapeHtml(item.why)}</p><p><b>Targets</b><br>${escapeHtml(item.target_muscles)}</p><p><b>Form cue</b><br>${escapeHtml(item.cue)}</p><p><b>Safety</b><br>${escapeHtml(item.safetyCue)}</p></section></main>`; }
function renderPlan() {
  const template=currentTemplate(), tier=state.preferences.tier, source=template.days?.[state.dayIndex]||{}, allowed=new Set(targetGroupsForDay(state.dayIndex)), baseIds=new Set(planSlots(displayPlan(state.dayIndex)).map(slot=>slot.exercise?.id)), rawCandidates=source.candidates||source.slots?.flatMap(slot=>[slot.primary,slot.alternative,slot.third].filter(Boolean))||[], candidates=rawCandidates.map(item=>libraryBySlug(item.slug||item.name)).filter(item=>item&&(item.levels?.includes(tier) ?? true)&&!baseIds.has(item.id)&&!isStretchOrMobility(item)&&inferredGroups(item).length&&inferredGroups(item).every(group=>allowed.has(group))); const extras=state.extras.filter(item=>item.day_index===state.dayIndex);
  const activeDay=template.days?.[state.dayIndex]||v5Routine[state.dayIndex];
  const planCandidates=candidates.filter(item=>!extras.some(extra=>extra.exercise_id===item.id));
  app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">MY TRAINING PLAN</p><h1>Build your week</h1><p>V5 uses six core exercises per day. Current workout history never changes.</p></div></section><section class="card"><form id="training-preferences" class="stack"><label class="field">Training template<select name="template_key"><option value="v5ppl" ${state.preferences.template_key==='v5ppl'?'selected':''}>V5 Optimized PPL (recommended)</option><option value="fitness7" ${state.preferences.template_key==='fitness7'?'selected':''}>Fitness 7 split</option></select></label><label class="field">Training level<select name="tier">${Object.entries(training.levels).map(([key,value])=>`<option value="${key}" ${tier===key?'selected':''}>${value.label} — ${value.subtitle}</option>`).join('')}</select></label><p class="muted">${template.fixedSlots||training.levels[tier]?.slots||6} core exercises per day · up to 2 optional extras · ${escapeHtml(training.levels[tier]?.rir||'1–2 reps in reserve')}</p><button class="button">Apply my future plan</button></form></section><section class="section-title"><div><p class="eyebrow">${activeDay?.day||'Day'} OPTIONS</p><h2>Optional extras</h2><p>Only related muscle groups are shown. Tap ＋ Add to save up to two.</p></div></section><section class="card stack">${optionalCards(planCandidates)}${extras.map((item,index)=>`<article class="compact-row"><span>${escapeHtml(item.exercise?.name||'Extra exercise')}</span><button type="button" class="pill" data-remove-extra="${index}">− Remove</button></article>`).join('')||'<p class="muted">No extras saved for this day yet.</p>'}</section><div class="day-picker">${(template.days||v5Routine).map((day,index)=>`<button class="day-chip ${state.dayIndex===index?'selected':''}" data-plan-day="${index}">${day.day.slice(0,3)}</button>`).join('')}</div></main>`;
}
function renderHabits() { const weekday=new Date().getDay(); app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">TODAY’S HABITS</p><h1>Keep the simple wins</h1><p>Binary tracking only—no calorie counting.</p></div></section><section class="card workout-list">${state.habitTemplate.map(item=>`<article class="compact-row"><span>${escapeHtml(item.label)}${item.id==='weekend-portions'&&weekday!==0&&weekday!==6?' <small>(weekend only)</small>':''}</span><label class="check"><input type="checkbox" data-habit="${escapeHtml(item.id)}" ${state.habitLog?.[item.id]?'checked':''}><span>Done</span></label></article>`).join('')}</section></main>`; }
function renderHistory(){ const session=calendarSessionForDate(state.historyDate), snap=session?.plan_snapshot||{}, progress=session?.progress||emptyProgress(), rings=ringStatus(session), legacy=session?.source_version!=='v5'; if(!session){state.screen='profile';render();return;} const selected=(slot,index)=>{const choice=progress.choices?.[index]||0;return choice===2&&slot.third?slot.third:choice===1&&slot.alternative?slot.alternative:slot.exercise;}; app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="profile">‹ Back to calendar</button><section class="detail-hero"><p class="eyebrow">${legacy?'V4 LEGACY · READ-ONLY SESSION':'V5 · READ-ONLY SESSION'}</p><h1>${escapeHtml(state.historyDate)}</h1><p>${escapeHtml(snap.focus||'Workout')}</p></section><section class="ring-summary"><span class="ring-label"><i class="ring ring-main ${rings.main?'complete':''}"></i>Main ${rings.main?'complete':'incomplete'}</span><span class="ring-label"><i class="ring ring-warmup ${rings.warmup?'complete':''}"></i>Warm-up ${rings.warmup?'complete':'incomplete'}</span><span class="ring-label"><i class="ring ring-recovery ${rings.recovery?'complete':''}"></i>Recovery ${rings.recovery?'complete':'incomplete'}</span></section><section class="section-title"><div><p class="eyebrow">MAIN WORKOUT</p><h2>Completed exercises</h2></div></section><section class="history-list">${(snap.slots||[]).map((slot,index)=>`<article class="card history-row"><div><b>${escapeHtml(selected(slot,index)?.name||'Exercise')}</b><small>${escapeHtml(slot.exercise?.name||'')}</small></div><span>${progress.slots?.[index]?'✓':'—'}</span></article>`).join('')}</section><section class="section-title"><div><p class="eyebrow">PREPARATION & RECOVERY</p><h2>Optional progress</h2></div></section><section class="history-list">${(snap.warmup||[]).map((item,index)=>`<article class="card history-row"><div><b>${escapeHtml(item.title||item.name)}</b><small>Warm-up</small></div><span>${progress.warmup?.[index]?'✓':'—'}</span></article>`).join('')}${(snap.recovery||[]).map((item,index)=>`<article class="card history-row"><div><b>${escapeHtml(item.title||item.name)}</b><small>Recovery</small></div><span>${progress.recovery?.[index]?'✓':'—'}</span></article>`).join('')}</section></main>`; }
function renderProfile(){ const membership=state.membership||{}; app.innerHTML=`<main class="shell">${header()}${banner()}${notice()}<button class="link-button" data-screen="home">‹ Home</button><section class="section-title"><div><p class="eyebrow">MY ACCOUNT</p><h1>${escapeHtml(state.profile?.full_name||'Member')}</h1></div></section><section class="profile-grid"><article class="card"><h2>Membership</h2><p class="membership-badge ${escapeHtml(membership.status||'')}">${escapeHtml(membership.status||'Not set')}</p><p>${membership.ends_on?`Ends ${escapeHtml(membership.ends_on)}`:'Membership date not set'}</p></article><article class="card"><h2>Training</h2><p>${escapeHtml(currentTemplate().name||'Personal plan')} · ${escapeHtml(training.levels[state.preferences.tier]?.label||'Intermediate')}</p><button class="pill" data-screen="plan">Edit plan</button></article></section>${calendarMarkup(false)}<section class="section-title"><div><p class="eyebrow">SESSION LIST</p><h2>Recent sessions</h2></div></section><section class="history-list">${state.sessions.length?state.sessions.map(session=>`<button class="card history-row history-button" data-history-date="${escapeHtml(session.session_date)}"><div><b>${escapeHtml(session.plan_snapshot?.focus||'Workout')}</b><small>${escapeHtml(session.session_date)}</small></div><span>${Object.values(session.progress?.slots||{}).filter(Boolean).length}/${session.plan_snapshot?.slots?.length||0}</span></button>`).join(''):'<article class="card empty">No saved workouts yet.</article>'}</section><section class="utility"><button class="button secondary" data-sign-out>Sign out</button></section></main>`; }
function render(){ if(!state.user) return renderSignIn(); if(state.screen==='detail') return renderDetail(); if(state.screen==='history') return renderHistory(); if(state.screen==='workout') return renderWorkout(); if(state.screen==='plan') return renderPlan(); if(state.screen==='habits') return renderHabits(); if(state.screen==='profile') return renderProfile(); renderHome(); }

function demoData(){ const data=readDemoMember(v5Routine); data.personal ||= {preferences:{template_key:'v5ppl',tier:'intermediate'},extras:[],habitTemplate:training.habitDefaults,habitLog:{}}; data.personal.preferences ||= {template_key:'v5ppl',tier:'intermediate'}; return data; }
function routineDemoPlans(){ return v5Routine.map((day,day_index)=>{const plan=routinePlan(day_index,v5Routine,'v5');return {id:`demo-plan-${state.user.id}-${day_index}`,member_id:state.user.id,day_index,focus:plan.focus,warmup:plan.warmup,recovery:plan.recovery,member_plan_slots:plan.member_plan_slots.map(slot=>({...slot,exercise_id:slot.exercise?.id,alternative_exercise_id:slot.alternative?.id||null,third_exercise_id:slot.third?.id||null}))};}); }
function loadDemoMember(){ const data=demoData(); state.demo=true; state.user={id:data.profile.id,email:MEMBER_USERNAME}; state.profile=data.profile; state.membership=data.membership; state.sessions=(data.sessions||[]).map(session=>({...session,source_version:session.source_version||'v5'})); state.library=training.catalog.map((item,index)=>normalizeExercise({...item,id:`demo-library-${item.slug||index}`})); state.preferences=data.personal.preferences; if(data.personal.planVersion!==5){data.plans=routineDemoPlans();data.personal.preferences={template_key:'v5ppl',tier:'intermediate'};data.personal.planVersion=5;data.sessions=[];writeDemoMember(data);} state.plans=data.plans; state.extras=(data.personal.extras||[]).map(item=>({...item,exercise:state.library.find(ex=>ex.id===item.exercise_id)})); state.habitTemplate=data.personal.habitTemplate||training.habitDefaults; state.habitLog=data.personal.habitLog||{}; render(); }
async function loadMember(){ const core=await Promise.all([supabase.from('profiles').select('*').eq('id',state.user.id).single(),supabase.from('memberships').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('member_weekly_plans').select('*,member_plan_slots(*,exercise:exercise_library!member_plan_slots_exercise_id_fkey(*),alternative:exercise_library!member_plan_slots_alternative_exercise_id_fkey(*))').eq('member_id',state.user.id).order('day_index'),supabase.from('workout_sessions').select('*').eq('member_id',state.user.id).order('session_date',{ascending:false}).limit(90),supabase.from('exercise_library').select('*').eq('active',true).order('name')]); if(core[0].error) throw core[0].error; [state.profile,state.membership,state.plans,state.sessions]=[core[0].data,core[1].data,core[2].data||[],core[3].data||[]]; state.library=(core[4].data||[]).map(item=>normalizeExercise({...item,levels:item.metadata?.levels||['beginner','intermediate','expert']})); const today=iso(new Date()); const feature=await Promise.all([supabase.from('member_training_preferences').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('member_extra_templates').select('*,exercise:exercise_library(*)').eq('member_id',state.user.id),supabase.from('member_habit_templates').select('*').eq('member_id',state.user.id).maybeSingle(),supabase.from('daily_habit_logs').select('*').eq('member_id',state.user.id).eq('log_date',today).maybeSingle()]); state.preferences=feature[0].data||state.preferences; if(state.preferences.template_key==='ppl') state.preferences={...state.preferences,template_key:'v5ppl'}; state.extras=(feature[1].data||[]).map(item=>({...item,exercise:normalizeExercise(item.exercise)})); state.habitTemplate=feature[2].data?.habits||training.habitDefaults; state.habitLog=feature[3].data?.checks||{}; render(); }
async function saveProgress(group,index,value){ const date=iso(scheduledDate(state.dayIndex)),plan=displayPlan(state.dayIndex),existing=sessionForDate(date),dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex),session=existing||{member_id:state.user.id,session_date:date,day_index:state.dayIndex,source_version:'v5',plan_snapshot:snapshot(plan,dayExtras),progress:emptyProgress()}; session.progress[group][index]=value; if(state.demo){state.sessions=[session,...state.sessions.filter(item=>!(item.session_date===date&&item.source_version==='v5'))]; const data=demoData(); data.sessions=state.sessions; writeDemoMember(data);return;} const {data,error}=await supabase.from('workout_sessions').upsert(session,{onConflict:'member_id,session_date,source_version'}).select().single();if(error)throw error;state.sessions=[data,...state.sessions.filter(item=>!(item.session_date===date&&item.source_version==='v5'))]; }
async function saveHabit(id,value){ state.habitLog[id]=value; if(state.demo){const data=demoData();data.personal.habitLog=state.habitLog;writeDemoMember(data);return;} const {error}=await supabase.from('daily_habit_logs').upsert({member_id:state.user.id,log_date:iso(new Date()),checks:state.habitLog},{onConflict:'member_id,log_date'});if(error)throw error; }
async function applyPlan(values){ const template=training.templates[values.template_key], tier=values.tier, limit=template.fixedSlots||training.levels[tier].slots, plans=[]; for(let index=0;index<6;index++){const source=template.days[index], candidates=(source.candidates||[]).map(item=>libraryBySlug(item.slug||item.name)).filter(Boolean).filter(item=>!item.levels||item.levels.includes(tier)); const selected=(values.template_key==='fitness7'||values.template_key==='v5ppl') ? source.slots.map(slot=>libraryBySlug(slot.primary.slug||slot.primary.name)).filter(Boolean) : candidates.slice(0,limit); if(selected.length<(values.template_key==='fitness7'?source.slots.length:limit)||selected.some(item=>!item?.id)) throw new Error(`Not enough approved ${training.levels[tier].label} exercises for ${source.day||routine[index].day}.`); plans.push({day_index:index,focus:source.focus,warmup:source.warmup?.steps||source.warmup||[],recovery:source.finish?.steps||source.recovery||[],slots:selected.map((exercise,position)=>({position,exercise_id:exercise.id,alternative_exercise_id:libraryBySlug(source.slots?.[position]?.alternative?.slug||source.slots?.[position]?.alternative?.name)?.id||null}))}); } if(state.demo){const data=demoData();data.personal.preferences={template_key:values.template_key,tier};data.plans=plans.map(plan=>({id:`demo-plan-${state.user.id}-${plan.day_index}`,member_id:state.user.id,...plan,member_plan_slots:plan.slots.map(slot=>({...slot,id:`demo-slot-${plan.day_index}-${slot.position}`,exercise:state.library.find(item=>item.id===slot.exercise_id),alternative:state.library.find(item=>item.id===slot.alternative_exercise_id)}))}));data.personal.planVersion=5;writeDemoMember(data);loadDemoMember();return;} for(const planData of plans){const {data:plan,error}=await supabase.from('member_weekly_plans').upsert({member_id:state.user.id,day_index:planData.day_index,focus:planData.focus,warmup:planData.warmup,recovery:planData.recovery},{onConflict:'member_id,day_index'}).select().single();if(error)throw error;const remove=await supabase.from('member_plan_slots').delete().eq('plan_id',plan.id);if(remove.error)throw remove.error;const insert=await supabase.from('member_plan_slots').insert(planData.slots.map(slot=>({...slot,plan_id:plan.id})));if(insert.error)throw insert.error;} const pref=await supabase.from('member_training_preferences').upsert({member_id:state.user.id,template_key:values.template_key,tier},{onConflict:'member_id'});if(pref.error)throw pref.error; await loadMember(); }

document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{state.message='';if(button.dataset.detailKey){state.detailItem=detailItem(button.dataset.detailKey);state.screen='detail';render();return;}if(button.dataset.closeDetail!==undefined){state.detailItem=null;state.screen='workout';render();return;}if(button.dataset.openExtras!==undefined){state.showExtras=true;render();return;}if(button.dataset.closeExtras!==undefined){state.showExtras=false;render();return;}if(button.dataset.calendarShift){const shift=Number(button.dataset.calendarShift);state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()+shift,1);render();return;}if(button.dataset.historyDate){state.historyDate=button.dataset.historyDate;state.screen='history';render();return;}if(button.dataset.addExtra){await addExtra(button.dataset.addExtra);return;}if(button.dataset.screen){state.screen=button.dataset.screen;state.showExtras=false;render();return;}if(button.dataset.day!==undefined){state.dayIndex=Number(button.dataset.day);state.screen='workout';state.showExtras=false;render();return;}if(button.dataset.planDay!==undefined){state.dayIndex=Number(button.dataset.planDay);render();return;}if(button.dataset.showReset!==undefined){document.querySelector('#request-reset').classList.toggle('hidden');return;}if(button.dataset.choice!==undefined){await saveProgress('choices',button.dataset.choice,Number(button.dataset.choiceIndex));render();return;}if(button.dataset.removeExtra!==undefined){const extras=state.extras.filter(item=>item.day_index===state.dayIndex);const target=extras[Number(button.dataset.removeExtra)];if(!target)return;if(state.demo){const data=demoData();data.personal.extras=data.personal.extras.filter(item=>!(item.day_index===state.dayIndex&&item.exercise_id===target.exercise_id));writeDemoMember(data);loadDemoMember();}else{const {error}=await supabase.from('member_extra_templates').delete().eq('member_id',state.user.id).eq('day_index',state.dayIndex).eq('exercise_id',target.exercise_id);if(error)throw error;await loadMember();}return;}if(button.dataset.clearSession){if(state.demo){state.sessions=state.sessions.filter(item=>item.session_date!==button.dataset.clearSession);const data=demoData();data.sessions=state.sessions;writeDemoMember(data);}else{const {error}=await supabase.from('workout_sessions').delete().eq('member_id',state.user.id).eq('session_date',button.dataset.clearSession);if(error)throw error;state.sessions=state.sessions.filter(item=>item.session_date!==button.dataset.clearSession);}render();return;}if(button.dataset.signOut!==undefined){if(state.demo){clearDemoSession('member');state.demo=false;state.user=null;state.profile=null;render();}else{await supabase.auth.signOut();localStorage.removeItem(preferenceKey);sessionStorage.removeItem(preferenceKey);state.user=null;render();}}}catch(error){state.message=error.message;render();}});
document.addEventListener('click',async event=>{const button=event.target.closest('button[data-add-guided]');if(!button)return;try{await addGuidedExtra(button.dataset.addGuidedPanel||'warmup',button.dataset.addGuided);}catch(error){state.message=error.message;render();}});
document.addEventListener('change',async event=>{try{if(event.target.dataset.check!==undefined){await saveProgress(event.target.dataset.check,event.target.dataset.index,event.target.checked);render();}if(event.target.dataset.habit!==undefined){await saveHabit(event.target.dataset.habit,event.target.checked);render();}}catch(error){state.message=error.message;render();}});
document.addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));try{if(event.target.id==='sign-in'){const username=String(values.username||'').trim();if(config.demoMode&&isDemoCredential('member',username,values.password)){saveDemoSession('member',values.remember==='on');loadDemoMember();return;}if(!username.includes('@'))throw new Error(demoAccountMessage);const remember=values.remember==='on';localStorage.removeItem(preferenceKey);sessionStorage.removeItem(preferenceKey);(remember?localStorage:sessionStorage).setItem(preferenceKey,remember?'remembered':'temporary');supabase=createSupabase(remember);const {data,error}=await supabase.auth.signInWithPassword({email:username,password:values.password});if(error)throw error;state.user=data.user;await loadMember();return;}if(event.target.id==='request-reset'){const {error}=await supabase.auth.resetPasswordForEmail(values.email,{redirectTo:location.origin});if(error)throw error;state.message='Check your email for the secure reset link.';render();}if(event.target.id==='training-preferences'){await applyPlan(values);state.message='Your future training plan is ready.';state.screen='home';render();}if(event.target.id==='extra-form'){const dayExtras=state.extras.filter(item=>item.day_index===state.dayIndex);if(dayExtras.length>=2)throw new Error('Keep optional extras to two for recovery.');const exercise=state.library.find(item=>item.id===values.exercise_id)||training.catalog.find(item=>item.id===values.exercise_id);if(!exercise)throw new Error('Choose an approved exercise.');if(state.demo){const data=demoData();data.personal.extras.push({day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id});writeDemoMember(data);loadDemoMember();}else{const {error}=await supabase.from('member_extra_templates').upsert({member_id:state.user.id,day_index:state.dayIndex,position:dayExtras.length,exercise_id:exercise.id},{onConflict:'member_id,day_index,position'});if(error)throw error;await loadMember();}state.showExtras=false;state.screen='workout';render();}}catch(error){state.message=error.message;render();}});
if(config.demoMode&&restoreDemoSession('member'))loadDemoMember();else if(supabase){const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(state.user)await loadMember();else render();}else render();
